# Generated by Django 4.0.7 on 2024-02-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('gpid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('dataNascimento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('tamanhoCamiseta', models.CharField(max_length=5)),
                ('restricaoAlimentar', models.CharField(max_length=20)),
                ('restricaoAlimentarRazao', models.CharField(max_length=100, null=True)),
                ('necessidade', models.CharField(max_length=20)),
                ('necessidadeRazao', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('telefoneContato', models.CharField(max_length=20)),
                ('contatoEmergencia', models.CharField(max_length=100)),
                ('telefoneEmergencia', models.CharField(max_length=20)),
                ('necessitaTransporteAereo', models.BooleanField(default=False)),
                ('planoChegada', models.CharField(max_length=255)),
                ('duvidaSugestao', models.TextField(null=True)),
            ],
        ),
    ]
