# Generated by Django 4.0.7 on 2024-02-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparecimento',
            name='dataNascimento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comparecimento',
            name='duvidaSugestao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparecimento',
            name='necessitaTransporteAereo',
            field=models.CharField(max_length=20),
        ),
    ]
