from django.db import models

# Create your models here.
class Comparecimento(models.Model):
    nomeCompleto = models.CharField(max_length=100)
    gpid = models.CharField(max_length=20)
    email = models.EmailField()
    departamento = models.CharField(max_length=100)
    regiao = models.CharField(max_length=100)
    nivel = models.CharField(max_length=100)
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14)
    dataNascimento = models.CharField(max_length=20)
    genero = models.CharField(max_length=10)
    tamanhoCamiseta = models.CharField(max_length=5)
    restricaoAlimentar = models.CharField(max_length=20)
    restricaoAlimentarRazao = models.CharField(max_length=100, null=True)
    necessidade = models.CharField(max_length=20)
    necessidadeRazao = models.CharField(max_length=100, null=True)
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=255)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=20)
    telefoneContato = models.CharField(max_length=20)
    contatoEmergencia = models.CharField(max_length=100)
    telefoneEmergencia = models.CharField(max_length=20)
    necessitaTransporteAereo = models.CharField(max_length=20)
    planoChegada = models.CharField(max_length=255)
    duvidaSugestao = models.TextField(blank=True, null=True)